version: '2'

services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ../../backend:/backend
            - ../../frontend/dist:/frontend_client
            - ./site.conf:/etc/nginx/conf.d/default.conf
        depends_on:
          - frontend
    php:
        image: php:fpm
        volumes:
            - ../../backend:/backend
            - ../log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
            - ../../resources:/stock
            - ../../resources:/trades
    frontend:
        build:
            context: ./docker-frontend
        volumes:
            - ../../frontend:/frontend